name: Deploy to Production

on:
  push:
    branches:
      - master
      - main
  merge_group:  # Dodane, aby uruchomić po mergu PR

jobs:
  app-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit test
        run: pnpm test

      - name: Install Vercel CLI
        run: pnpm install -g vercel@latest

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel deploy --token ${VERCEL_TOKEN} --prod --yes
