name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    name: CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm run test

      - name: Build app
        run: npm run build

  deploy-preview:
    name: Deploy Preview to Vercel
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: 'Staging'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure node
        uses: ./.github/actions/setup-project

      - name: Deploy app to Vercel (Preview)
        uses: ./.github/actions/deploy-vercel
        with:
          mode: 'preview'
          vercel-token: ${{ secrets.VERCEL_TOKEN }}

      - name: Comment with preview URL
        uses: actions/github-script@v7
        env:
          DEPLOY_URL: ${{ env.DEPLOY_URL }}
        with:
          script: |
            const { DEPLOY_URL } = process.env;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔍 Preview URL: ${DEPLOY_URL}`
            });
